# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [ ]:
# 2. Create a random tensor with shape (7, 7)
import torch

tensor_A = torch.rand(7, 7)
tensor_A


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [ ]:
# 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7)
# (hint: you may have to transpose the second tensor)

tensor_B = torch.rand(1, 7)

# transpose the second tensor so shapes are compatible: (7,7) x (7,1)
output = torch.matmul(tensor_A, tensor_B.T)
output, output.shape


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [ ]:
# 4. Set the random seed to 0 and do 2 & 3 over again

torch.manual_seed(0)

tensor_A = torch.rand(7, 7)
tensor_B = torch.rand(1, 7)

output = torch.matmul(tensor_A, tensor_B.T)
output, output.shape


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
# 5. Speaking of random seeds, is there a GPU equivalent?
# Yes! It's torch.cuda.manual_seed()

if torch.cuda.is_available():
    torch.cuda.manual_seed(1234)
    print("GPU random seed set to 1234")
else:
    print("CUDA not available.")



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [ ]:
# 6. Create two random tensors of shape (2, 3) and send them both to the GPU
# Set torch.manual_seed(1234)

torch.manual_seed(1234)

device = "cuda" if torch.cuda.is_available() else "cpu"
print("Device:", device)

tensor_X = torch.rand(2, 3).to(device)
tensor_Y = torch.rand(2, 3).to(device)

tensor_X, tensor_Y



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [ ]:
# 7. Perform a matrix multiplication on the tensors you created in 6
# (you may have to adjust one tensor's shape)

result = torch.matmul(tensor_X, tensor_Y.T)
result, result.shape


### 8. Find the maximum and minimum values of the output of 7.

In [ ]:
# 8. Find the maximum and minimum values of the output of 7

max_val = result.max()
min_val = result.min()

max_val, min_val


### 9. Find the maximum and minimum index values of the output of 7.

In [ ]:
# 9. Find the maximum and minimum index values of the output of 7

argmax_val = result.argmax()
argmin_val = result.argmin()

argmax_val, argmin_val



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [ ]:
# 10. Make a random tensor with shape (1, 1, 1, 10)
# Remove the 1 dimensions to get a shape of (10)
# Set the seed to 7

torch.manual_seed(7)

tensor_Z = torch.rand(1, 1, 1, 10)
print(tensor_Z, tensor_Z.shape)

squeezed_Z = torch.squeeze(tensor_Z)
print(squeezed_Z, squeezed_Z.shape)
